line-length = 99

# Ignore complaints about bound lambda expressions
ignore = ["E731"]

[per-file-ignores]
"__init__.py" = ["F401"]  # Ignore unused imports in __init__.py
"utils.py" = ["F401"]  # Ignore unused import error - intentional for backwd-compat
